# Generated by Django 4.2.5 on 2024-03-20 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='invite_code',
            field=models.CharField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='customer',
            name='tokens',
            field=models.IntegerField(default=0),
        ),
    ]
