# Generated by Django 4.2.5 on 2024-03-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_customer_invite_code_customer_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='referer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='system.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='max_refers',
            field=models.IntegerField(default=10, verbose_name='Максимальное количество приглашений с одного аккаунта'),
        ),
    ]
