# Generated by Django 4.2.5 on 2024-03-21 15:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_customer_referer'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='referer_tokens',
            field=models.IntegerField(default=5000, verbose_name='Максимальное количество токенов за приглашение'),
        ),
        migrations.AddField(
            model_name='settings',
            name='subscription_price',
            field=models.FloatField(default=559, verbose_name='Стоимость подписки'),
        ),
        migrations.AddField(
            model_name='settings',
            name='text',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Текст подписки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='token_price',
            field=models.FloatField(default=0.01, verbose_name='Cтоимость одного токена'),
        ),
        migrations.AddField(
            model_name='settings',
            name='tokens_in_subscription',
            field=models.IntegerField(default=100000, verbose_name='Токенов в подписке'),
        ),
    ]
