# Generated by Django 4.2.5 on 2024-03-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_subscriptions_options_subscriptions_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactions',
            name='tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.IntegerField(choices=[(0, 'Оплата подписки'), (1, 'Покупка токенов'), (2, 'Оплата подписки и токенов')], default=0),
        ),
    ]
