# Generated by Django 4.2.5 on 2024-04-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_transactions_paid_transactions_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='end',
            field=models.DateField(verbose_name='Окончания'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='start',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customer', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='method',
            field=models.IntegerField(choices=[(0, 'Оплата картой(ЮКасса)'), (1, 'Оплата токенами TON')], default=0, verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='tokens',
            field=models.IntegerField(default=0, verbose_name='Количество токенов'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.IntegerField(choices=[(0, 'Оплата подписки'), (1, 'Покупка токенов'), (2, 'Оплата подписки и токенов')], default=0, verbose_name='Тип транзакции'),
        ),
    ]
