# Generated by Django 4.2.5 on 2024-04-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_remove_ticketmessage_ticket_delete_ticket_and_more'),
        ('system', '0010_alter_customer_name_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Subscriptions',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
