# Generated by Django 4.2.5 on 2024-05-06 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_customer_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='audio',
            new_name='audio_file',
        ),
    ]
