# Generated by Django 4.2.5 on 2024-04-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_states',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_types',
            field=models.CharField(choices=[('DIPLOMA_CHAT_TYPE', 'DIPLOMA_CHAT_TYPE')], default='DIPLOMA_CHAT_TYPE', max_length=50),
        ),
    ]
