# Generated by Django 4.2.5 on 2024-04-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_chat_chat_states_chat_chat_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_states',
            new_name='chat_state',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='chat_types',
            new_name='chat_type',
        ),
    ]
