# Generated by Django 4.2.5 on 2024-04-24 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_customer_transactions_subscriptions'),
        ('messenger', '0005_message_response_specific_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system.customer', verbose_name='Клиент'),
            preserve_default=False,
        ),
    ]
