# Generated by Django 4.2.5 on 2024-04-26 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='messenger.chat', verbose_name='Чат'),
            preserve_default=False,
        ),
    ]
