# Generated by Django 4.2.5 on 2024-05-12 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0010_audiochat_audiomessage_audiochatfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.audiochat', verbose_name='Чат'),
        ),
    ]
