# Generated by Django 4.2.5 on 2024-05-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0013_merge_0010_helpchat_0012_alter_audiochat_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpChat',
        ),
    ]
