# Generated by Django 4.2.5 on 2024-05-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0014_delete_helpchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_link',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения'),
        ),
    ]
