# Generated by Django 4.2.5 on 2024-03-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'Новый'), (1, 'Решается'), (2, 'Решен')]),
        ),
    ]
