# Generated by Django 4.2.5 on 2024-04-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmessage',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketMessage',
        ),
    ]
